export const DOMAIN_ORGANIC = "DOMAIN_ORGANIC";
export const DOMAIN_PAID = "DOMAIN_PAID";
export const COMPETITORS_ORGANIC = "COMPETITORS_RESEARCH";
export const COMPETITORS_PAID = "COMPETITORS_PAID";
export const COMPETITORS_BACKLINKS = "COMPETITORS_BACKLINKS";
export const MAIN_COMPETITOR = "MAIN_COMPETITOR";
export const DOMAIN_SUBMIT = "DOMAIN_SUBMIT";
